version: "3"
services:
  autorate-frontend:
    image: pridhvi/autorate-frontend:latest
    deploy:
      replicas: 3
    ports:
      - "8080:8080"
    networks:
      - autorate
  autorate-backend:
    image: pridhvi/autorate-backend:latest
    deploy:
      replicas: 3
    ports:
      - "8081:8081"
    networks:
      - autorate

networks:
  autorate:
    external: true
